/**
 * KKEEY Portfolio — Inhaltsdatei v3.5
 * Hier alle Texte, Projekte, Skills und Timeline pflegen.
 * Multilingual: DE / EN / FR / UK / PL
 * E-Mails: kuck_kevin@icloud.com · Kkeey_IT@iCloud.com
 */
window.KK_DATA = {

  // ─── HERO ───────────────────────────────────────────────────────────────────
  hero: {
    name: 'Kevin Kuck',
    greeting: {
      de: 'Hallo, ich bin',
      en: "Hi, I'm",
      fr: 'Bonjour, je suis',
      uk: 'Привіт, я',
      pl: 'Cześć, jestem',
    },
    tagline: 'IT · AI · AUDIO · 15+ JAHRE PRAXIS',
    roles: {
      de: [
        'AI Systems Engineer',
        'Voice AI & Automation Specialist',
        'Local-First & RAG Architekturen',
        'DJ & Audio Systems Engineer',
        'KMU Prozess-Automatisierer',
      ],
      en: [
        'AI Systems Engineer',
        'Voice AI & Automation Specialist',
        'Local-First & RAG Architectures',
        'DJ & Audio Systems Engineer',
        'SME Automation Specialist',
      ],
      fr: [
        'Ingénieur Systèmes IA',
        'Spécialiste Voice AI & Automatisation',
        'Architectures Local-First & RAG',
        'DJ & Ingénieur Systèmes Audio',
        'Automatisation des Processus PME',
      ],
      uk: [
        'AI Systems Engineer',
        'Спеціаліст із Voice AI та автоматизації',
        'Архітектури Local-First & RAG',
        'DJ & Інженер аудіосистем',
        'Автоматизація процесів для бізнесу',
      ],
      pl: [
        'AI Systems Engineer',
        'Specjalista ds. Voice AI i Automatyzacji',
        'Architektury Local-First & RAG',
        'DJ & Inżynier Systemów Audio',
        'Automatyzacja Procesów dla MŚP',
      ],
    },
    cta1: {
      de: 'Projekte ansehen',
      en: 'View Projects',
      fr: 'Voir les projets',
      uk: 'Переглянути проєкти',
      pl: 'Zobacz projekty',
    },
    cta2: {
      de: 'Kontakt aufnehmen',
      en: 'Get in touch',
      fr: 'Me contacter',
      uk: 'Зв\'язатися',
      pl: 'Skontaktuj się',
    },
    cta3: {
      de: 'Bewerbungsmappe (PDF)',
      en: 'Application Portfolio (PDF)',
      fr: 'Dossier de candidature (PDF)',
      uk: 'Резюме / Портфоліо (PDF)',
      pl: 'Dokumenty aplikacyjne (PDF)',
    },
    available: {
      de: 'Verfügbar ab sofort',
      en: 'Available now',
      fr: 'Disponible immédiatement',
      uk: 'Доступний зараз',
      pl: 'Dostępny od zaraz',
    },
  },

  // ─── TRIO / DIFFERENTIATORS ──────────────────────────────────────────────────
  trio: [
    {
      icon: '⚙️',
      label: {
        de: 'Operationale Tiefe',
        en: 'Operational Depth',
        fr: 'Profondeur Opérationnelle',
        uk: 'Операційна глибина',
        pl: 'Doświadczenie Operacyjne',
      },
      sub: {
        de: '15 J. Inventory & Supply Chain · BAUHAUS',
        en: '15 Yrs Inventory & Supply Chain · BAUHAUS',
        fr: '15 ans Gestion des Stocks · BAUHAUS',
        uk: '15 років Inventory & Supply Chain · BAUHAUS',
        pl: '15 lat Zarządzanie Magazynem · BAUHAUS',
      },
      detail: {
        de: 'Systemdenken aus dem echten Handelsbetrieb. Ich weiß wie operative KMU wirklich funktionieren — nicht aus Büchern, sondern aus 15 Jahren täglicher Praxis.',
        en: 'Systems thinking from real-world operations. I know how SMEs actually function — not from theory, but 15 years of hands-on practice.',
        fr: 'Pensée systémique issue de l\'exploitation commerciale réelle. Je connais le fonctionnement concret des PME — forgé par 15 ans de pratique quotidienne.',
        uk: 'Системне мислення з реального сектору торгівлі. Я знаю, як насправді працює бізнес — не з книжок, а з 15 років щоденної практики.',
        pl: 'Myślenie systemowe z realnego środowiska handlowego. Wiem, jak w praktyce funkcjonują operacje MŚP — nie z książek, lecz z 15 lat codziennego doświadczenia.',
      },
    },
    {
      icon: '🤖',
      label: {
        de: 'AI Systems & Automation',
        en: 'AI Systems & Automation',
        fr: 'Systèmes IA & Automatisation',
        uk: 'AI Системи & Автоматизація',
        pl: 'Systemy AI & Automatyzacja',
      },
      sub: {
        de: '100% From Scratch · GitHub Actions · Cloud Run',
        en: '100% From Scratch · GitHub Actions · Cloud Run',
        fr: '100% From Scratch · GitHub Actions · Cloud Run',
        uk: '100% From Scratch · GitHub Actions · Cloud Run',
        pl: '100% From Scratch · GitHub Actions · Cloud Run',
      },
      detail: {
        de: 'Ich baue Agentensysteme komplett ohne Frameworks auf der grünen Wiese – jeder Code-Ordner startet leer mit einer CLAUDE.md oder AGENT.md. Deployments laufen via Docker, GitHub Actions und Google Cloud Run.',
        en: 'I build agent systems entirely from scratch without frameworks – every code folder starts empty with a CLAUDE.md or AGENT.md. Deployments run via Docker, GitHub Actions, and Google Cloud Run.',
        fr: 'Je conçois des systèmes d\'agents entièrement sur mesure — chaque projet démarre de zéro avec CLAUDE.md ou AGENT.md. Déploiements via Docker, GitHub Actions et Google Cloud Run.',
        uk: 'Я створюю агентні системи повністю з нуля — кожен проєкт починається з порожньої папки та файлу CLAUDE.md або AGENT.md. Розгортання через Docker, GitHub Actions та Cloud Run.',
        pl: 'Buduję systemy agentowe całkowicie od zera — każdy projekt startuje z pustego folderu z plikiem CLAUDE.md lub AGENT.md. Wdrożenia przez Docker, GitHub Actions i Google Cloud Run.',
      },
    },
    {
      icon: '🎚️',
      label: {
        de: 'Audio & DJ Engineering',
        en: 'Audio & DJ Engineering',
        fr: 'Ingénierie Audio & DJ',
        uk: 'Audio & DJ Інженерія',
        pl: 'Inżynieria Dźwięku & DJ',
      },
      sub: {
        de: '10 Jahre · 5.000+ Tracks · Traktor Pro · Rekordbox',
        en: '10 Years · 5,000+ Tracks · Traktor Pro · Rekordbox',
        fr: '10 ans · 5.000+ morceaux · Traktor Pro · Rekordbox',
        uk: '10 років · 5 000+ треків · Traktor Pro · Rekordbox',
        pl: '10 lat · 5000+ utworów · Traktor Pro · Rekordbox',
      },
      detail: {
        de: 'Tiefe Domainkenntnis in Audio-DSP, harmonischem Mixen und Musikanalyse. Fundament für AuraTone AI.',
        en: 'Deep domain knowledge in audio DSP, harmonic mixing, and music analysis. The foundation of AuraTone AI.',
        fr: 'Expertise approfondie en traitement du signal audio (DSP), mixage harmonique et analyse musicale. Fondation d\'AuraTone AI.',
        uk: 'Глибокі знання в області Audio DSP, гармонійного зведення та аналізу музики. Фундамент для AuraTone AI.',
        pl: 'Głęboka wiedza w zakresie cyfrowego przetwarzania sygnałów audio (DSP), miksowania harmonicznego i analizy muzycznej. Fundament projektu AuraTone AI.',
      },
    },
  ],

  // ─── PROJEKTE ───────────────────────────────────────────────────────────────────
  projects: [
    {
      id: 'claire-v25-native-audio',
      repo: 'KKEEY92/claire-v2.5-native-audio',
      status: { latestTag: 'v2.5.0', sourceVisibility: 'private' },
      name: 'Claire V2.5 Native Audio',
      color: '#00d4aa',
      colorRgb: '0,212,170',
      tag: '● Produktiv v2.5 · Local-First · Native Audio',
      sub: {
        de: 'Voice AI Agent · Full-Duplex · ~200ms Latenz · Local LLM Switch',
        en: 'Voice AI Agent · Full-Duplex · ~200ms Latency · Local LLM Switch',
        fr: 'Agent Vocal IA · Full-Duplex · Latence ~200ms · Switch LLM Local',
        uk: 'Голосовий AI-агент · Full-Duplex · Затримка ~200мс · Локальний LLM Switch',
        pl: 'Głosowy Agent AI · Full-Duplex · Opóźnienie ~200ms · Przełącznik Lokalnego LLM',
      },
      desc: {
        de: 'Lokaler Native-Audio Voice AI Agent (separates Projekt zu Claire V2). Die Implementierung ist privat. Öffentliche Architekturdokumentation und ein Latenz-Nachweis stehen zur externen Prüfung bereit.',
        en: 'Local native-audio voice AI agent (a separate project from Claire V2). The implementation is private. Public architecture documentation and a latency evidence artifact are available for external review.',
        fr: 'Agent vocal native-audio local (projet distinct de Claire V2). L\'implémentation est privée. Documentation d\'architecture publique et preuve de latence disponibles.',
        uk: 'Локальний native-audio голосовий AI-агент (окремий проєкт від Claire V2). Реалізація приватна. Публічна архітектура та доказ затримки доступні для ознайомлення.',
        pl: 'Lokalny agent głosowy native-audio (osobny projekt względem Claire V2). Implementacja jest prywatna. Publiczna dokumentacja architektury i dowód opóźnienia są dostępne.',
      },
      stack: ['Python 3.13', 'LiveKit Agents 2.x', 'Gemini 2.5 Flash', 'LM Studio (Local LLM)', 'Silero VAD', 'Google Drive RAG', 'React / Vite'],
      note: {
        de: 'Source privat. Öffentlich: Architektur und bereinigter Latenz-Nachweis (~200 ms, lokaler Verarbeitungsschritt).',
        en: 'Source is private. Public: architecture docs and a sanitized latency evidence artifact (~200 ms, defined local processing step).',
        fr: 'Code source privé. Public : architecture et preuve de latence (~200 ms).',
        uk: 'Код приватний. Публічно: архітектура та доказ затримки (~200 мс).',
        pl: 'Kod źródłowy prywatny. Publicznie: architektura i dowód opóźnienia (~200 ms).',
      },
      links: [
        { href: 'https://github.com/KKEEY92/Claire-V2-Architecture', label: { de: 'Architektur →', en: 'Architecture →', fr: 'Architecture →', uk: 'Архітектура →', pl: 'Architektura →' } },
        { href: 'https://kkeey.dev/evidence/benchmarks/claire-latency-001.json', label: { de: 'Latenz-Nachweis →', en: 'Latency evidence →', fr: 'Preuve de latence →', uk: 'Доказ затримки →', pl: 'Dowód opóźnienia →' } },
      ],
    },
    {
      id: 'auratone-ai',
      repo: 'KKEEY92/AuraTone-AI-by-KKEEy',
      status: { type: 'implemented', codeVersion: '2.0.0', latestTag: 'v1.3.0', sourceVisibility: 'private', publicBinaryRelease: false },
      name: 'AuraTone AI Desktop',
      color: '#f7a841',
      colorRgb: '247,168,65',
      sub: {
        de: 'Native Audio-Analyse-Workstation · Tauri · Rust · Python DSP',
        en: 'Native Audio Analysis Workstation · Tauri · Rust · Python DSP',
        fr: 'Station d\'Analyse Audio Native · Tauri · Rust · Python DSP',
        uk: 'Нативна станція аналізу аудіо · Tauri · Rust · Python DSP',
        pl: 'Natywna Stacja Analizy Dźwięku · Tauri · Rust · Python DSP',
      },
      desc: {
        de: 'Native Desktop-Anwendung mit Tauri-/Rust-Kern und Python-DSP-Pipeline für lokale Audioanalyse. Die Implementierung ist privat. Öffentliche Architekturdokumentation und bereinigte technische Nachweise stehen zur externen Prüfung bereit.',
        en: 'Native desktop application with a Tauri/Rust core and a Python DSP pipeline for local audio analysis. The implementation is private. Public architecture documentation and sanitized technical evidence are available for external review.',
        fr: 'Application de bureau native avec cœur Tauri/Rust et pipeline DSP Python pour l\'analyse audio locale. Documentation d\'architecture publique et preuves techniques auditées disponibles.',
        uk: 'Нативна програма для комп\'ютера з ядром Tauri/Rust та конвеєром Python DSP для локального аналізу аудіо. Публічна документація архітектури та перевірені технічні звіти доступні для ознайомлення.',
        pl: 'Natywna aplikacja desktopowa z rdzeniem Tauri/Rust i pipeline\'em Python DSP do lokalnej analizy dźwięku. Dostępna publiczna dokumentacja architektury oraz zweryfikowane dowody techniczne.',
      },
      stack: ['Tauri 2', 'Rust', 'React 19', 'Python DSP', 'ffmpeg ebur128', 'librosa', 'SQLite', 'Metal Shader + CPU-Fallback'],
      note: {
        de: 'Die private Codebasis führt Version 2.0.0. Der im technischen Audit zuletzt festgestellte Git-Tag ist v1.3.0. Ein öffentlicher Binärrelease liegt derzeit nicht vor.',
        en: 'The private codebase identifies as version 2.0.0. The latest Git tag identified during the technical audit is v1.3.0. No public binary release is currently available.',
        fr: 'La base de code privée correspond à la version 2.0.0. Le dernier tag Git audité est v1.3.0.',
        uk: 'Приватна кодова база відповідає версії 2.0.0. Останній зафіксований Git-тег — v1.3.0.',
        pl: 'Prywatny kod źródłowy identyfikuje się jako wersja 2.0.0. Ostatni zweryfikowany tag Git to v1.3.0.',
      },
      links: [
        { href: 'https://github.com/KKEEY92/AuraTone-Architecture/blob/master/evidence/README.md', label: { de: 'Architektur →', en: 'Architecture →', fr: 'Architecture →', uk: 'Архітектура →', pl: 'Architektura →' } },
        { href: 'https://github.com/KKEEY92/AuraTone-Architecture/blob/master/evidence/DSP_VALIDATION.md', label: { de: 'DSP-Nachweis →', en: 'DSP Validation →', fr: 'Validation DSP →', uk: 'Перевірка DSP →', pl: 'Walidacja DSP →' } },
        { href: 'https://github.com/KKEEY92/AuraTone-Architecture/blob/master/evidence/examples/library_analysis.sample.json', label: { de: 'Beispielanalyse →', en: 'Example Analysis →', fr: 'Exemple d\'analyse →', uk: 'Приклад аналізу →', pl: 'Przykładowa analiza →' } },
        { href: 'https://github.com/KKEEY92/AuraTone-Architecture/blob/master/evidence/LIMITATIONS.md', label: { de: 'Evidenzgrenzen →', en: 'Evidence Limitations →', fr: 'Limites de preuve →', uk: 'Межі доказів →', pl: 'Ograniczenia dowodowe →' } },
      ],
    },
    {
      id: 'ai-virtual-calling',
      repo: 'KKEEY92/AI-Virtual-Calling-and-Write-a-friend',
      status: { latestTag: null },
      name: 'AI Virtual Calling',
      color: '#f43f5e',
      colorRgb: '244,63,94',
      tag: '● Demo / Prototype · WebRTC · React',
      sub: {
        de: 'Gemini Live Voice UI mit Video-Avatar',
        en: 'Gemini Live Voice UI with Video Avatar',
        fr: 'Interface Vocale Gemini Live avec Avatar',
        uk: 'Голосовий інтерфейс Gemini Live з відео-аватаром',
        pl: 'Interfejs głosowy Gemini Live z awatarem wideo',
      },
      desc: {
        de: 'Full-Stack WebRTC-Applikation. React-Frontend mit Tailwind (Liquid Glass Design) kommuniziert über WebSockets und FastAPI mit der Gemini Multimodal Live API. Echtzeit-Sprache, Avatar-Animation und Screen-Sharing.',
        en: 'Full-stack WebRTC application. React frontend with Tailwind (Liquid Glass Design) communicates via WebSockets & FastAPI with Gemini Multimodal Live API. Real-time voice, video avatar animation & screen sharing.',
        fr: 'Application WebRTC Full-Stack. Frontend React avec design Liquid Glass communicant via WebSockets & FastAPI avec l\'API Gemini Multimodal Live. Voix en temps réel, avatar animé et partage d\'écran.',
        uk: 'Full-Stack WebRTC застосунок. React-фронтенд з дизайном Liquid Glass взаємодіє через WebSockets та FastAPI з Gemini Multimodal Live API. Голос у реальному часі, анімація аватара та показ екрана.',
        pl: 'Aplikacja WebRTC full-stack. Frontend React z interfejsem Liquid Glass komunikuje się przez WebSockets i FastAPI z Gemini Multimodal Live API. Głos w czasie rzeczywistym, animacja awatara i udostępnianie ekranu.',
      },
      stack: ['React', 'TypeScript', 'WebRTC', 'Python FastAPI', 'Gemini Multimodal Live API'],
      link: 'https://github.com/KKEEY92/AI-Virtual-Calling-and-Write-a-friend',
      linkLabel: {
        de: 'Auf GitHub ansehen →',
        en: 'View on GitHub →',
        fr: 'Voir sur GitHub →',
        uk: 'Переглянути на GitHub →',
        pl: 'Zobacz na GitHubie →',
      },
    },
    {
      id: 'afm-3-chat',
      repo: 'KKEEY92/afm-chat',
      status: { latestTag: null },
      name: 'AFM-3 Chat',
      color: '#3b82f6',
      colorRgb: '59,130,246',
      tag: '● Local macOS App · Apple Foundation Model',
      sub: {
        de: 'Swift WKWebView · Apple Foundation Model · Offline',
        en: 'Swift WKWebView · Apple Foundation Model · Offline',
        fr: 'Swift WKWebView · Apple Foundation Model · Hors-ligne',
        uk: 'Swift WKWebView · Apple Foundation Model · Офлайн',
        pl: 'Swift WKWebView · Apple Foundation Model · Offline',
      },
      desc: {
        de: 'Native macOS-App mit Swift WKWebView für das Apple Foundation Model (AFM-3-Core) — 100% lokal ohne Cloud. Matrix Rain UI, Obsidian Vault RAG, macOS say Neural TTS, ComfyUI Bildgenerierung & Push-to-Talk.',
        en: 'Native macOS app with Swift WKWebView for Apple Foundation Model (AFM-3-Core) — 100% local without cloud. Matrix Rain UI, Obsidian Vault RAG, macOS say Neural TTS, ComfyUI image gen & Push-to-Talk.',
        fr: 'Application macOS native avec Swift WKWebView pour Apple Foundation Model (AFM-3-Core) — 100% locale sans cloud. UI Matrix Rain, Obsidian Vault RAG, synthèse vocale neuronale macOS, ComfyUI et Push-to-Talk.',
        uk: 'Нативний застосунок для macOS зі Swift WKWebView для Apple Foundation Model (AFM-3-Core) — 100% локально без хмари. Інтерфейс Matrix Rain, Obsidian Vault RAG, нейронний TTS macOS, генерація ComfyUI та Push-to-Talk.',
        pl: 'Natywna aplikacja macOS ze Swift WKWebView dla Apple Foundation Model (AFM-3-Core) — 100% lokalna, bez chmury. Interfejs Matrix Rain, Obsidian Vault RAG, neuronowy TTS w macOS, generowanie obrazów ComfyUI i Push-to-Talk.',
      },
      stack: ['Swift / WKWebView', 'Python http.server', 'Apple AFM-3-Core', 'ComfyUI API', 'macOS Neural TTS'],
      link: 'https://github.com/KKEEY92/afm-chat',
      linkLabel: {
        de: 'Auf GitHub ansehen →',
        en: 'View on GitHub →',
        fr: 'Voir sur GitHub →',
        uk: 'Переглянути на GitHub →',
        pl: 'Zobacz na GitHubie →',
      },
    },
    {
      id: 'architecture-documentation',
      repo: 'KKEEY92/Claire-V2-Architecture',
      status: { type: 'documentation', codeVersion: null, latestTag: null },
      name: 'Architecture Documentation',
      color: '#94a3b8',
      colorRgb: '148,163,184',
      sub: {
        de: 'C4-Architekturdokumentation zu Claire V2 & AuraTone AI',
        en: 'C4 architecture documentation for Claire V2 & AuraTone AI',
        fr: 'Documentation d\'architecture C4 pour Claire V2 & AuraTone AI',
        uk: 'C4-документація архітектури для Claire V2 & AuraTone AI',
        pl: 'Dokumentacja architektury C4 dla Claire V2 i AuraTone AI',
      },
      desc: {
        de: 'Öffentliche Architekturdokumentation für private und öffentlich einsehbare Implementierungsvarianten.',
        en: 'Public architecture documentation for private and publicly accessible implementation variants.',
        fr: 'Documentation publique d\'architecture pour les variantes d\'implémentation privées et publiques.',
        uk: 'Публічна архітектурна документація для приватних та відкритих варіантів реалізації.',
        pl: 'Publiczna dokumentacja architektury dla wariantów implementacji prywatnych oraz open-source.',
      },
      stack: ['C4-Modell', 'Mermaid', 'System Context', 'Container Architecture', 'Voice Pipeline', 'Memory Architecture', 'Desktop Architecture'],
      links: [
        { href: 'https://github.com/KKEEY92/Claire-V2-Architecture', label: { de: 'Claire V2 Architektur →', en: 'Claire V2 architecture →', fr: 'Architecture Claire V2 →', uk: 'Архітектура Claire V2 →', pl: 'Architektura Claire V2 →' } },
        { href: 'https://github.com/KKEEY92/AuraTone-Architecture', label: { de: 'AuraTone Architektur →', en: 'AuraTone architecture →', fr: 'Architecture AuraTone →', uk: 'Архітектура AuraTone →', pl: 'Architektura AuraTone →' } },
      ],
    },
    {
      id: 'sortiere-py',
      repo: 'KKEEY92/sortiere.py',
      status: { latestTag: null },
      name: 'sortiere.py',
      color: '#22c55e',
      colorRgb: '34,197,94',
      tag: '● CLI Utility v1.0 · Open Source',
      sub: {
        de: 'Universeller CLI Datei-Organizer · Python 3.12',
        en: 'Universal CLI File Organizer · Python 3.12',
        fr: 'Organiseur de Fichiers CLI · Python 3.12',
        uk: 'Універсальний CLI сортувальник файлів · Python 3.12',
        pl: 'Uniwersalny Organizer Plików CLI · Python 3.12',
      },
      desc: {
        de: 'Intelligenter Datei-Organizer mit token-basiertem Matching, Dry-Run-Modus und 5-Pillar-Kategorisierung. Sortiert beliebige Verzeichnisse nach konfigurierbaren Regeln.',
        en: 'Smart file organizer with token-based matching, dry-run mode, and 5-pillar categorization. Sorts any directory by configurable rules.',
        fr: 'Organiseur de fichiers intelligent avec filtrage par jetons, mode simulation et catégorisation en 5 piliers.',
        uk: 'Розумний сортувальник файлів із токенним зіставленням, тестовим режимом Dry-Run та категоризацією за 5 стовпами.',
        pl: 'Inteligentny organizer plików z dopasowywaniem tokenowym, trybem symulacji (dry-run) i 5-filarową kategoryzacją.',
      },
      stack: ['Python 3.12', 'CLI / argparse', 'OS / Pathlib', 'Token Matching', 'Dry-Run Mode'],
      link: 'https://github.com/KKEEY92',
      linkLabel: {
        de: 'GitHub-Profil →',
        en: 'GitHub profile →',
        fr: 'Profil GitHub →',
        uk: 'Профіль GitHub →',
        pl: 'Profil GitHub →',
      },
    },
  ],

  // ─── ZERTIFIZIERUNGEN ─────────────────────────────────────────────────────────────────
  certifications: [
    {
      name: 'Microsoft KI-Grundlagen',
      color: '#0ea5e9',
      colorRgb: '14,165,233',
      tag: '✓ Microsoft Certified',
      sub: {
        de: 'Zertifizierung · 2026',
        en: 'Certification · 2026',
        fr: 'Certification · 2026',
        uk: 'Сертифікація · 2026',
        pl: 'Certyfikacja · 2026',
      },
      desc: {
        de: 'Offizielle Microsoft-Zertifizierung zu KI-Grundlagen — Konzepte, Einsatzbereiche und verantwortungsvoller Umgang mit generativer KI.',
        en: 'Official Microsoft certification covering AI fundamentals — concepts, use cases, and responsible use of generative AI.',
        fr: 'Certification Microsoft officielle sur les fondamentaux de l\'IA — concepts, cas d\'usage et IA générative responsable.',
        uk: 'Офіційна сертифікація Microsoft щодо основ ШІ — концепції, сфери застосування та відповідальне використання генеративного ШІ.',
        pl: 'Oficjalny certyfikat Microsoft dotyczący podstaw sztucznej inteligencji — koncepcje, zastosowania i odpowiedzialna generatywna sztuczna inteligencja.',
      },
      link: 'https://www.linkedin.com/in/kevin-kuck-it/details/certifications/',
      linkLabel: {
        de: 'Nachweis auf LinkedIn →',
        en: 'View credential on LinkedIn →',
        fr: 'Voir sur LinkedIn →',
        uk: 'Переглянути на LinkedIn →',
        pl: 'Zobacz poświadczenie na LinkedIn →',
      },
    },
  ],

  // ─── WEITERBILDUNG ──────────────────────────────────────────────────────────────────
  education: {
    label: {
      de: 'Weiterbildung',
      en: 'Further education',
      fr: 'Formations continues',
      uk: 'Підвищення кваліфікації',
      pl: 'Kształcenie ustawiczne',
    },
    linkedinLink: 'https://www.linkedin.com/in/kevin-kuck-it/details/certifications/',
    linkedinLabel: {
      de: 'Alle Nachweise auf LinkedIn ansehen →',
      en: 'View all credentials on LinkedIn →',
      fr: 'Voir tous les certificats sur LinkedIn →',
      uk: 'Усі сертифікати на LinkedIn →',
      pl: 'Zobacz wszystkie certyfikaty na LinkedIn →',
    },
    items: [
      {
        de: 'Grundwissen Generative KI · Microsoft & LinkedIn Learning Lernpfad (4 Std. 25 Min.) — Mai 2026',
        en: 'Generative AI Foundations · Microsoft & LinkedIn Learning path (4h 25min) — May 2026',
        fr: 'Fondamentaux de l\'IA générative · Microsoft & LinkedIn Learning (4h 25min) — Mai 2026',
        uk: 'Основи генеративного ШІ · Microsoft & LinkedIn Learning (4 год. 25 хв.) — Трав 2026',
        pl: 'Podstawy Generatywnej AI · Ścieżka szkoleniowa Microsoft & LinkedIn Learning (4 godz. 25 min.) — Maj 2026',
      },
      {
        de: 'Was ist Generative KI? · LinkedIn Learning + PMI — Mai 2026',
        en: 'What Is Generative AI? · LinkedIn Learning + PMI — May 2026',
        fr: 'Qu\'est-ce que l\'IA générative ? · LinkedIn Learning + PMI — Mai 2026',
        uk: 'Що таке генеративний ШІ? · LinkedIn Learning + PMI — Трав 2026',
        pl: 'Czym jest Generatywna AI? · LinkedIn Learning + PMI — Maj 2026',
      },
      {
        de: 'Generative KI: Die Entwicklung einer durchdachten Online-Suche · LinkedIn Learning + PMI — Mai 2026',
        en: 'Generative AI: Developing Thoughtful Online Search · LinkedIn Learning + PMI — May 2026',
        fr: 'IA générative : recherche en ligne réfléchie · LinkedIn Learning + PMI — Mai 2026',
        uk: 'Генеративний ШІ: Розвиток продуманого онлайн-пошуку · LinkedIn Learning + PMI — Трав 2026',
        pl: 'Generatywna AI: Rozwój przemyślanego wyszukiwania online · LinkedIn Learning + PMI — Maj 2026',
      },
      {
        de: 'Künstliche Intelligenz Grundlagen · LinkedIn Learning — 2026',
        en: 'Artificial Intelligence Foundations · LinkedIn Learning — 2026',
        fr: 'Fondations de l\'Intelligence Artificielle · LinkedIn Learning — 2026',
        uk: 'Основи штучного інтелекту · LinkedIn Learning — 2026',
        pl: 'Podstawy Sztucznej Inteligencji · LinkedIn Learning — 2026',
      },
      {
        de: 'Mit KI zusammenarbeiten · LinkedIn Learning — 2026',
        en: 'Collaborating with AI · LinkedIn Learning — 2026',
        fr: 'Collaborer avec l\'IA · LinkedIn Learning — 2026',
        uk: 'Співпраця зі штучним інтелектом · LinkedIn Learning — 2026',
        pl: 'Współpraca z AI · LinkedIn Learning — 2026',
      },
      {
        de: 'Medienkompetenz im KI-Zeitalter — 2026',
        en: 'Media Literacy in the AI Era — 2026',
        fr: 'Éducation aux médias à l\'ère de l\'IA — 2026',
        uk: 'Медіаграмотність в епоху ШІ — 2026',
        pl: 'Edukacja medialna w erze AI — 2026',
      },
      {
        de: 'Active Directory-Verwaltung automatisieren mit PowerShell · LinkedIn Learning — Mai 2026',
        en: 'Automating Active Directory Management with PowerShell · LinkedIn Learning — May 2026',
        fr: 'Automatisation d\'Active Directory avec PowerShell · LinkedIn Learning — Mai 2026',
        uk: 'Автоматизація керування Active Directory за допомогою PowerShell · LinkedIn Learning — Трав 2026',
        pl: 'Automatyzacja zarządzania Active Directory za pomocą PowerShell · LinkedIn Learning — Maj 2026',
      },
    ],
  },

  // ─── SKILLS ───────────────────────────────────────────────────────────────────────
  skillGroups: [
    {
      label: {
        de: 'Sprachen & Core Code',
        en: 'Languages & Core Code',
        fr: 'Langages & Code Core',
        uk: 'Мови & Core Code',
        pl: 'Języki & Główny Kod',
      },
      skills: [
        { name: 'Python 3.12+ (AsyncIO, FastAPI)', pct: 92 },
        { name: 'TypeScript',                      pct: 85 },
        { name: 'JavaScript / React 19 / Vite 6',   pct: 82 },
        { name: 'PowerShell Automatisierung',      pct: 82 },
        { name: 'HTML5 / Modern Vanilla CSS',      pct: 88 },
        { name: 'Rust / Tauri 2.0 (Native Core)',   pct: 75 },
      ],
    },
    {
      label: {
        de: 'AI, Agents & Voice',
        en: 'AI, Agents & Voice',
        fr: 'IA, Agents & Voix',
        uk: 'AI, Агенти & Voice',
        pl: 'AI, Agenci & Voice',
      },
      skills: [
        { name: 'From-Scratch Agent Architekturen', pct: 95 },
        { name: 'Gemini API / Vertex AI',           pct: 94 },
        { name: 'LiveKit 2.x Agents (Voice AI)',    pct: 92 },
        { name: 'Local LLMs (LM Studio, Qwen2.5)',  pct: 88 },
        { name: 'RAG Systems (Drive & Obsidian RAG)', pct: 86 },
        { name: 'ComfyUI / Multimodal AI',          pct: 82 },
      ],
    },
    {
      label: {
        de: 'Systeme, Cloud & DevOps',
        en: 'Systems, Cloud & DevOps',
        fr: 'Systèmes, Cloud & DevOps',
        uk: 'Системи, Cloud & DevOps',
        pl: 'Systemy, Cloud & DevOps',
      },
      skills: [
        { name: 'Active Directory & Entra ID (IAM)', pct: 88 },
        { name: 'Docker & Containerization',        pct: 85 },
        { name: 'Google Cloud Run & Serverless',    pct: 85 },
        { name: 'GitHub Actions (CI/CD Pipelines)', pct: 84 },
        { name: 'FastAPI / Node.js Backend',        pct: 80 },
        { name: 'SQLite / PostgreSQL / Firebase',   pct: 82 },
      ],
    },
    {
      label: {
        de: 'Audio DSP & Enterprise Ops',
        en: 'Audio DSP & Enterprise Ops',
        fr: 'Audio DSP & Opérations Enterprise',
        uk: 'Audio DSP & Enterprise Ops',
        pl: 'Audio DSP & Operacje Enterprise',
      },
      skills: [
        { name: 'Traktor Pro 4 / Rekordbox',        pct: 95 },
        { name: 'Inventory Management & Supply Chain', pct: 95 },
        { name: 'Audio DSP (librosa, ffmpeg)',      pct: 85 },
        { name: 'Apple Metal GPU Acceleration',     pct: 80 },
        { name: 'KRITIS IT & Endpoint Security',    pct: 85 },
      ],
    },
  ],

  // ─── KARRIERE TIMELINE ─────────────────────────────────────────────────────────────
  timeline: [
    {
      period: {
        de: 'bis Ende 2024 · 15 Jahre',
        en: 'Until end 2024 · 15 years',
        fr: 'jusqu\'à fin 2024 · 15 ans',
        uk: 'до кінця 2024 · 15 років',
        pl: 'do końca 2024 · 15 lat',
      },
      role: {
        de: 'Inventory Management & IT-Operations',
        en: 'Inventory Management & IT Operations',
        fr: 'Gestion des Stocks & Opérations IT',
        uk: 'Керування інвентарем та IT-операції',
        pl: 'Zarządzanie Zapasami & Operacje IT',
      },
      company: 'BAUHAUS',
      color: '#7c6af7',
      active: false,
      desc: {
        de: '15 Jahre operative Tiefe in Inventory Management und Supply Chain. Systemdenken im Handelsbetrieb — diese Erfahrung wirkt heute als direkter AI-Differenziator.',
        en: '15 years of operational depth in inventory management and supply chain. Systems thinking that is now a direct AI differentiator.',
        fr: '15 ans d\'expérience opérationnelle en gestion des stocks et logistique. Une vision systémique qui constitue aujourd\'hui un différenciateur direct en ingénierie IA.',
        uk: '15 років практичного досвіду в управлінні запасами та ланцюгами постачання. Системне мислення, яке сьогодні є прямою перевагою в розробці ШІ.',
        pl: '15 lat praktyki operacyjnej w zarządzaniu stanami magazynowymi i łańcuchem dostaw. Myślenie systemowe stanowiące dziś bezpośredni wyróżnik w inżynierii AI.',
      },
      tags: ['Inventory', 'Supply Chain', 'Prozessoptimierung', 'Systemdenken'],
    },
    {
      period: {
        de: 'Dez 2025 – Mai 2026',
        en: 'Dec 2025 – May 2026',
        fr: 'Déc 2025 – Mai 2026',
        uk: 'Груд 2025 – Трав 2026',
        pl: 'Gru 2025 – Maj 2026',
      },
      role: {
        de: 'IT-Administrator',
        en: 'IT Administrator',
        fr: 'Administrateur IT',
        uk: 'IT-Адміністратор',
        pl: 'Administrator IT',
      },
      company: 'Johanniter Bundes-IT',
      color: '#7c6af7',
      active: false,
      desc: {
        de: 'Verantwortlich für Benutzer-, Gruppen- und Berechtigungsmanagement in Active Directory und Microsoft Entra ID sowie für die strukturierte Bearbeitung von Incidents in ITIL-orientierten Supportprozessen. Weiterer Scope: Citrix (NetScaler), Omnitracker, Innovaphone PBX. Windows-11-Rollouts via Deskcenter Studio & Custom-PowerShell (Pausierung 46%-Update zur Speed-Optimierung). Endpoint-Security via FortiClient & Sophos. Eigene Ticket-Automation & der KKEEY-Standard.',
        en: 'Responsible for user, group and permission management in Active Directory and Microsoft Entra ID, and for structured incident resolution in ITIL-oriented support processes. Additional scope: Citrix (NetScaler), Omnitracker, Innovaphone PBX. Windows 11 rollouts via Deskcenter Studio & custom PowerShell (pausing 46% update for speed optimization). Endpoint security via FortiClient & Sophos. Custom ticket automation & the KKEEY Standard.',
        fr: 'Gestion des identités, groupes et permissions dans Active Directory et Microsoft Entra ID, résolution structurée d\'incidents ITIL. Citrix (NetScaler), Omnitracker, téléphonie PBX. Déploiements Windows 11 via Deskcenter Studio et PowerShell. Sécurité FortiClient & Sophos. Automatisation des tickets et standard KKEEY.',
        uk: 'Керування користувачами, групами та правами доступу в Active Directory та Microsoft Entra ID, вирішення інцидентів за процесами ITIL. Citrix (NetScaler), Omnitracker, PBX. Розгортання Windows 11 через Deskcenter Studio та PowerShell. Безпека FortiClient & Sophos. Власна автоматизація тікетів та стандарт KKEEY.',
        pl: 'Zarządzanie użytkownikami, grupami i uprawnieniami w Active Directory oraz Microsoft Entra ID, strukturalne rozwiązywanie incydentów w procesach ITIL. Citrix (NetScaler), Omnitracker, PBX. Wdrażanie Windows 11 przez Deskcenter Studio i PowerShell. Bezpieczeństwo FortiClient & Sophos. Autorska automatyzacja zgłoszeń i standard KKEEY.',
      },
      tags: ['Active Directory', 'Entra ID', 'IAM', 'Citrix', 'Deskcenter Studio', 'PowerShell', 'KRITIS', 'FortiClient'],
    },
    {
      period: {
        de: 'seit Juni 2026',
        en: 'since June 2026',
        fr: 'depuis Juin 2026',
        uk: 'з Червня 2026',
        pl: 'od Czerwca 2026',
      },
      role: {
        de: 'AI-Architekt & Entwickler',
        en: 'AI Architect & Developer',
        fr: 'Architecte IA & Développeur',
        uk: 'AI-Архітектор & Розробник',
        pl: 'Architekt AI & Programista',
      },
      company: {
        de: 'Selbstständig / Freelance',
        en: 'Self-employed / Freelance',
        fr: 'Indépendant / Freelance',
        uk: 'Самозайнятий / Фріланс',
        pl: 'Działalność / Freelance',
      },
      color: '#00d4aa',
      active: true,
      desc: {
        de: 'Aufbau von AI-Agent-Systemen für KMU. Claire V2.5 und AuraTone AI als öffentliche Proof-of-Work-Projekte.',
        en: 'Building AI agent systems for SMEs. Claire V2.5 and AuraTone AI as public proof-of-work projects.',
        fr: 'Conception de systèmes d\'agents IA pour PME. Claire V2.5 et AuraTone AI comme projets publics de démonstration.',
        uk: 'Створення агентних систем ШІ для малого та середнього бізнесу. Claire V2.5 та AuraTone AI як публічні проєкти підтвердження експертизи.',
        pl: 'Tworzenie systemów agentów AI dla sektora MŚP. Claire V2.5 oraz AuraTone AI jako publiczne projekty potwierdzające kompetencje.',
      },
      tags: ['AI Agents', 'Python', 'Gemini API', 'KMU Automation', 'Freelance'],
    },
  ],

  // ─── I18N STRINGS ────────────────────────────────────────────────────────────────
  i18n: {
    navAbout:      { de: 'Über mich',                   en: 'About',          fr: 'À propos',        uk: 'Про мене',         pl: 'O mnie' },
    navProjects:   { de: 'Projekte',                    en: 'Projects',       fr: 'Projets',         uk: 'Проєкти',          pl: 'Projekty' },
    navSkills:     { de: 'Skills',                      en: 'Skills',         fr: 'Compétences',     uk: 'Навички',          pl: 'Umiejętności' },
    navCerts:      { de: 'Zertifikate',                 en: 'Certifications', fr: 'Certifications',  uk: 'Сертифікати',      pl: 'Certyfikaty' },
    navCareer:     { de: 'Karriere',                    en: 'Career',         fr: 'Parcours',        uk: 'Кар\'єра',         pl: 'Kariera' },
    navContact:    { de: 'Kontakt',                     en: 'Contact',        fr: 'Contact',         uk: 'Контакти',         pl: 'Kontakt' },
    trioLabel:     { de: 'Differenziator',              en: 'Differentiator', fr: 'Différenciateur', uk: 'Відмінна риса',    pl: 'Wyróżnik' },
    trioTitle:     { de: 'Das seltene Dreierpaket',     en: 'The Rare Trio',  fr: 'Le Trio Unique',  uk: 'Унікальне 3-в-1',  pl: 'Unikalne Trio Kompetencji' },
    trioSub:       { de: 'Drei Domänen. Eine Person. Diese Kombination gibt es kaum.', en: 'Three domains. One person. Almost no one has this combination.', fr: 'Trois domaines. Une personne. Une combinaison rare.', uk: 'Три домени. Одна людина. Рідкісна комбінація експертизи.', pl: 'Trzy domeny. Jedna osoba. Niezwykle rzadkie połączenie.' },
    projTitle:     { de: 'Projekte & Showcase',         en: 'Projects & Showcase', fr: 'Projets & Showcase', uk: 'Проєкти & Showcase', pl: 'Projekty & Portfolio' },
    projSub:       { de: 'Gebaut. Deployed. Öffentlich.', en: 'Built. Deployed. Public.', fr: 'Conçu. Déployé. Public.', uk: 'Створено. Розгорнуто. Публічно.', pl: 'Zbudowane. Wdrożone. Publiczne.' },
    skillsTitle:   { de: 'Skills & Kompetenzprofil',   en: 'Skills & Expertise', fr: 'Compétences & Profil', uk: 'Навички & Профіль', pl: 'Umiejętności & Profil Ekspercki' },
    certLabel:     { de: 'Verifiziert',                 en: 'Verified',       fr: 'Vérifié',         uk: 'Перевірено',       pl: 'Zweryfikowano' },
    certTitle:     { de: 'Zertifizierungen',            en: 'Certifications', fr: 'Certifications',  uk: 'Сертифікації',     pl: 'Certyfikaty' },
    certEmpty:     { de: 'Zertifizierungen werden aktuell ergänzt — schau bald wieder vorbei.', en: 'Certifications are being added soon — check back shortly.', fr: 'Les certifications sont en cours d\'ajout.', uk: 'Сертифікати оновлюються — завітайте незабаром.', pl: 'Certyfikaty są obecnie aktualizowane — sprawdź wkrótce.' },
    careerLabel:   { de: 'Karriere',                    en: 'Career',         fr: 'Parcours',        uk: 'Кар\'єра',         pl: 'Kariera' },
    careerTitle:   { de: 'Beruflicher Werdegang',       en: 'Career Story',   fr: 'Parcours Professionnel', uk: 'Професійний шлях', pl: 'Ścieżka Zawodowa' },
    contactLabel:  { de: 'Kontakt',                     en: 'Contact',        fr: 'Contact',         uk: 'Контакти',         pl: 'Kontakt' },
    contactTitle:  { de: 'Lass uns sprechen.',          en: "Let's talk.",    fr: 'Échangeons ensemble.', uk: 'Почнімо діалог.', pl: 'Porozmawiajmy.' },
    contactDesc:   { de: 'Offen für Festanstellungen, Freelance-Projekte und Kollaborationen. Remote · Hybrid · DE, EN, FR, UK & PL.', en: 'Open for full-time roles, freelance projects, and collaborations. Remote · Hybrid · DE, EN, FR, UK & PL.', fr: 'Ouvert aux postes en CDI, missions freelance et collaborations. Télétravail · Hybride · DE, EN, FR, UK & PL.', uk: 'Відкритий до співпраці: постійна робота, фріланс-проєкти та колаборації. Віддалено · Гібрид · DE, EN, FR, UK & PL.', pl: 'Otwarty na stałe zatrudnienie, projekty freelance i współpracę. Remote · Hybrydowo · DE, EN, FR, UK & PL.' },
    namePH:        { de: 'Dein Name',                   en: 'Your name',      fr: 'Votre nom',       uk: 'Ваше ім\'я',       pl: 'Twoje imię i nazwisko' },
    emailPH:       { de: 'Deine E-Mail',                en: 'Your email',     fr: 'Votre e-mail',    uk: 'Ваш Email',        pl: 'Twój adres e-mail' },
    msgPH:         { de: 'Deine Nachricht...',          en: 'Your message...',fr: 'Votre message...',uk: 'Ваше повідомлення...', pl: 'Twoja wiadomość...' },
    submitLabel:   { de: 'Nachricht senden →',          en: 'Send message →', fr: 'Envoyer le message →', uk: 'Надіслати повідомлення →', pl: 'Wyślij wiadomość →' },
    sentMsg:       { de: '✓ Nachricht gesendet — ich melde mich.', en: "✓ Message sent — I'll get back to you.", fr: '✓ Message envoyé — réponse rapide.', uk: '✓ Повідомлення надіслано — я зв\'яжуся з вами.', pl: '✓ Wiadomość wysłana — odpowiem wkrótce.' },
    sendingLabel:  { de: 'Wird gesendet…',              en: 'Sending…',       fr: 'Envoi en cours…', uk: 'Надсилається…',     pl: 'Wysyłanie…' },
    sendErr:       { de: 'Fehler — bitte direkt mailen', en: 'Error — please email directly', fr: 'Erreur — écrivez directement', uk: 'Помилка — напишіть напряму', pl: 'Błąd — prosimy o bezpośredni kontakt' },
    darkBtnLight:  { de: 'Hellmodus aktivieren',        en: 'Switch to light mode', fr: 'Activer le mode clair', uk: 'Увімкнути світлу тему', pl: 'Włącz tryb jasny' },
    darkBtnDark:   { de: 'Dunkelmodus aktivieren',      en: 'Switch to dark mode', fr: 'Activer le mode sombre', uk: 'Увімкнути темну тему', pl: 'Włącz tryb ciemny' },
    footerCross:   { de: 'IT-Profil ansehen: Systemadministration · IAM →', en: 'View IT profile: system administration · IAM →', fr: 'Voir le profil IT : administration système · IAM →', uk: 'Переглянути IT-профіль: системне адміністрування · IAM →', pl: 'Zobacz profil IT: administracja systemami · IAM →' },
  },

};
